require './lib/board.rb'
require './lib/new_knight.rb'
require './lib/rook.rb'
require './lib/pathing.rb'
require './lib/pawn.rb'
require './lib/bishop.rb'
require './lib/queen.rb'
require './lib/king.rb'
